---
title: Meet the team
---

This project was developed by **\[STA1NANA]** For [STA 199: Introduction to Data Science and Statistical Thinking](https://sta199-s25.github.io/) at Duke University.

<<<<<<< HEAD
-   Team member 1: Ellie Armstrong is a junior from the suburbs outside of Chicago studying International Comparative Studies and Psychology.
-   Team member 2: Emma Chua is a freshman from Hong Kong studying Statistics and Computer Science.
-   Team member 3: Nikki Caparrelli is a freshman from Naples, Florida, studying Evolutionary Anthropology and Neuroscience.
-   Team member 4: Stephanie Sensel is a freshman from West Chester, New York, studying Public Policy.
-   ...
=======
The team is comprised of the following team members.
-   Ellie Armstrong: One sentence description of Team member 1 (e.g., year, major, etc.).
-   Team member 2: One sentence description of Team member 2 (e.g., year, major, etc.).
-   Team member 3: One sentence description of Team member 3 (e.g., year, major, etc.).
-   Team member 4: One sentence description of Team member 4 (e.g., year, major, etc.).
-   
>>>>>>> 3b44d4813b8be7081a07bfb29ad5383e351b9b80
