name: Render Website

on:
  workflow_dispatch:

jobs:
  render:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Render step
        run: |
          echo "Rendering website..."
          # Put your real rendering commands here
